server:
  port: 8081
spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: password

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 4
      failureRateThreshold: 50
      waitDurationInOpenState: 4s
      permittedNumberOfCallsInHalfOpenState: 4
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      #      ignoreExceptions:
#      recordFailurePredicate:

  instances:
    restaurantClient:
      baseConfig: default


resilience4j.retry:
  configs:
    default:
      registerHealthIndicator: true
      maxRetryAttempts: 2
  instances:
    restaurantnClient:
      baseConfig: default
feign:
  circuitbreaker:
    enabled: false
  hystrix:
    enabled: false

eureka:
  client:
    enabled: false
