server:
  port: 8081
spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/order?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password

resilience4j.circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - br.com.delivery.eats.order.client.exception.GenericBusinessException
    instances:
      restaurantClient:
        base-config: default


resilience4j.retry:
    configs:
      default:
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        maxAttempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - br.com.delivery.eats.order.client.exception.RestaurantClientException
    instances:
      restaurantClient:
        base-config: default
feign:
  circuitbreaker:
    enabled: false
  hystrix:
    enabled: false

eureka:
  client:
    enabled: false
